# Generated by Django 3.0.2 on 2020-01-04 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqquestion',
            options={'verbose_name': 'FAQ questions', 'verbose_name_plural': 'FAQ questions'},
        ),
        migrations.AlterModelOptions(
            name='faqsection',
            options={'verbose_name': 'FAQ section', 'verbose_name_plural': 'FAQ sections'},
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='answer_text',
            field=models.TextField(blank=True, help_text='Bei den Antworten funktioniert auch HTML-Syntax!<br> Aus Gründen des verwendeten CSS-Frameworks muss der Tag <strong>&lt;ul&gt;</strong> die CSS-Klasse <em>browser-default</em> besitzen!', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='question_text',
            field=models.TextField(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hjelp.FAQSection', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='show',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='faqsection',
            name='icon_color',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('brown', 'brown'), ('grey', 'grey'), ('blue-grey', 'blue-grey'), ('black', 'black'), ('white', 'white'), ('transparent', 'transparent')], default='black', max_length=20, verbose_name='Symbol colour'),
        ),
        migrations.AlterField(
            model_name='faqsection',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
