# Generated by Django 3.1.4 on 2020-12-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hjelp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqsection',
            name='show',
            field=models.BooleanField(default=False, verbose_name='Show'),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='extended_data',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='faqsection',
            name='extended_data',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='issuecategory',
            name='extended_data',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
