# Generated by Django 3.0.5 on 2020-04-13 09:59

from django.db import migrations

import ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hjelp", "0002_add_bug_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faqquestion",
            name="answer_text",
            field=ckeditor.fields.RichTextField(
                help_text="Because of our CSS framework the HTML tag <strong>&lt;ul&gt;</strong> must have the CSS class <em>browser-default</em>. In this case, please use the manual editor mode."
            ),
        ),
    ]
