# Generated by Django 3.0.5 on 2020-04-14 13:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hjelp", "0003_alter_faqquestion_answer_text_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqquestion",
            name="extended_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, editable=False
            ),
        ),
        migrations.AddField(
            model_name="faqsection",
            name="extended_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, editable=False
            ),
        ),
        migrations.AddField(
            model_name="rebuscategory",
            name="extended_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, editable=False
            ),
        ),
        migrations.AddField(
            model_name="support",
            name="extended_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, editable=False
            ),
        ),
    ]
